import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    SEARCH_REPORT: `${STATE_REDUCER_KEY}/SEARCH_REPORT`,
    UPDATE_VESSEL_INSPECTION: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION`,
    UPDATE_VESSEL_INSPECTION_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_REQUEST`,
    UPDATE_VESSEL_INSPECTION_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_SUCCESS`,
    UPDATE_VESSEL_INSPECTION_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_FAILURE`,

    SHOW_PREDICTIONS: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS`,
    SHOW_PREDICTIONS_REQUEST: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_REQUEST`,
    SHOW_PREDICTIONS_SUCCESS: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_SUCCESS`,
    SHOW_PREDICTIONS_FAILURE: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_FAILURE`,


    FETCH_INSPECTION_DETAILS: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS`,
    FETCH_INSPECTION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_REQUEST`,
    FETCH_INSPECTION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_SUCCESS`,
    FETCH_INSPECTION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_FAILURE`,

    GET_VESSEL_INSPECTION: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_DETAILS`,
    GET_VESSEL_INSPECTION_REQUEST: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_DETAILS_REQUEST`,
    GET_VESSEL_INSPECTION_SUCCESS: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_DETAILS_SUCCESS`,
    GET_VESSEL_INSPECTION_FAILURE: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_DETAILS_FAILURE`,

    SAVE_PREDICTED: `${STATE_REDUCER_KEY}/SAVE_PREDICTED_DETAILS`,
    SAVE_PREDICTED_REQUEST: `${STATE_REDUCER_KEY}/SAVE_PREDICTED_DETAILS_REQUEST`,
    SAVE_PREDICTED_SUCCESS: `${STATE_REDUCER_KEY}/SAVE_PREDICTED_DETAILS_SUCCESS`,
    SAVE_PREDICTED_FAILURE: `${STATE_REDUCER_KEY}/SAVE_PREDICTED_DETAILS_FAILURE`,

    REPORT_LIST: `${STATE_REDUCER_KEY}/REPORT_LIST_DETAILS`,
    REPORT_LIST_REQUEST: `${STATE_REDUCER_KEY}/REPORT_LIST_DETAILS_REQUEST`,
    REPORT_LIST_SUCCESS: `${STATE_REDUCER_KEY}/REPORT_LIST_DETAILS_SUCCESS`,
    REPORT_LIST_FAILURE: `${STATE_REDUCER_KEY}/REPORT_LIST_DETAILS_FAILURE`,

    REPORT_BY_ID: `${STATE_REDUCER_KEY}/REPORT_BY_ID`,
    REPORT_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/REPORT_BY_ID_REQUEST`,
    REPORT_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/REPORT_BY_ID_SUCCESS`,
    REPORT_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/REPORT_BY_ID_FAILURE`

};

export const updateVessel = createAction(ACTION_TYPES.UPDATE_VESSEL_INSPECTION);
export const showPredictions = createAction(ACTION_TYPES.SHOW_PREDICTIONS);
export const getInspectionDetails = createAction(ACTION_TYPES.GET_VESSEL_INSPECTION);
export const savePredicted = createAction(ACTION_TYPES.SAVE_PREDICTED);
export const fetchReports = createAction(ACTION_TYPES.REPORT_LIST);
export const searchReport = createAction(ACTION_TYPES.SEARCH_REPORT);
export const fetchReportById = createAction(ACTION_TYPES.REPORT_BY_ID);
