import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {


    FETCH_USER_BY_ID: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID`,
    FETCH_USER_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_REQUEST`,
    FETCH_USER_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_SUCCESS`,
    FETCH_USER_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_FAILURE`,

    FETCH_USERS_LIST: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST`,
    FETCH_USERS_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_REQUEST`,
    FETCH_USERS_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_SUCCESS`,
    FETCH_USERS_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_FAILURE`

};

export const fetchUserList = createAction(ACTION_TYPES.FETCH_USERS_LIST);

export const fetchUserById = createAction(ACTION_TYPES.FETCH_USER_BY_ID);
