import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {


    FETCH_USER_BY_ID: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID`,
    FETCH_USER_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_REQUEST`,
    FETCH_USER_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_SUCCESS`,
    FETCH_USER_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_FAILURE`,

    FETCH_USERS_LIST: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST`,
    FETCH_USERS_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_REQUEST`,
    FETCH_USERS_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_SUCCESS`,
    FETCH_USERS_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USERS_LIST_FAILURE`,

    FETCH_DASHBOARD_STATS: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_STATS`,
    FETCH_DASHBOARD_STATS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_STATS_REQUEST`,
    FETCH_DASHBOARD_STATS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_STATS_SUCCESS`,
    FETCH_DASHBOARD_STATS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_DASHBOARD_STATS_FAILURE`,

    FETCH_USERS: `${STATE_REDUCER_KEY}/FETCH_USERS`,
    FETCH_USERS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USERS_REQUEST`,
    FETCH_USERS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USERS_SUCCESS`,
    FETCH_USERS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USERS_FAILURE`,

    FETCH_VESSEL_LIST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST`,
    FETCH_VESSEL_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_REQUEST`,
    FETCH_VESSEL_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_SUCCESS`,
    FETCH_VESSEL_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_FAILURE`,

    RESET_PASSWORD: `${STATE_REDUCER_KEY}/RESET_PASSWORD`,
    RESET_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/RESET_PASSWORD_REQUEST`,
    RESET_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/RESET_PASSWORD_SUCCESS`,
    RESET_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/RESET_PASSWORD_FAILURE`

};

export const fetchUserList = createAction(ACTION_TYPES.FETCH_USERS_LIST);
export const fetchUserById = createAction(ACTION_TYPES.FETCH_USER_BY_ID);
export const fetchDashboardCards = createAction(ACTION_TYPES.FETCH_DASHBOARD_STATS);
export const fetchVessels = createAction(ACTION_TYPES.FETCH_VESSEL_LIST);
export const updateUser = createAction(ACTION_TYPES.FETCH_VESSEL_LIST);
export const resetPassword = createAction(ACTION_TYPES.RESET_PASSWORD);
