import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {

    LOG_OUT: `${STATE_REDUCER_KEY}/LOG_OUT`,

    NAVIGATE_TO: `${STATE_REDUCER_KEY}/NAVIGATE_TO`,
    REFRESH_CURRENT_PATH: `${STATE_REDUCER_KEY}/REFRESH_CURRENT_PATH`,

    COMMON_DOWNLOAD_FILE: `${STATE_REDUCER_KEY}/COMMON_DOWNLOAD_FILE`,
    COMMON_DOWNLOAD_FILE_REQUEST: `${STATE_REDUCER_KEY}/COMMON_DOWNLOAD_FILE_REQUEST`,
    COMMON_DOWNLOAD_FILE_SUCCESS: `${STATE_REDUCER_KEY}/COMMON_DOWNLOAD_FILE_SUCCESS`,
    COMMON_DOWNLOAD_FILE_FAILURE: `${STATE_REDUCER_KEY}/COMMON_DOWNLOAD_FILE_FAILURE`,

    RESEND_OTP: `${STATE_REDUCER_KEY}/RESEND_OTP`
};

export const logout = createAction(ACTION_TYPES.LOG_OUT);
export const navigateTo = createAction(ACTION_TYPES.NAVIGATE_TO);
export const refresh = createAction(ACTION_TYPES.REFRESH_CURRENT_PATH);
