import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_VESSEL_DETAILS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS`,
    FETCH_VESSEL_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_REQUEST`,
    FETCH_VESSEL_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_SUCCESS`,
    FETCH_VESSEL_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_FAILURE`,

    UPDATE_VESSEL: `${STATE_REDUCER_KEY}/UPDATE_VESSEL`,
    UPDATE_VESSEL_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_REQUEST`,
    UPDATE_VESSEL_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_SUCCESS`,
    UPDATE_VESSEL_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_FAILURE`

};

export const updateVessel = createAction(ACTION_TYPES.UPDATE_VESSEL);

export const fetchVesselInfoDetails = createAction(ACTION_TYPES.FETCH_VESSEL_DETAILS);

