import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    SIGN_IN: `${STATE_REDUCER_KEY}/SIGN_IN`,
    SIGN_IN_REQUEST: `${STATE_REDUCER_KEY}/SIGN_IN_REQUEST`,
    SIGN_IN_SUCCESS: `${STATE_REDUCER_KEY}/SIGN_IN_SUCCESS`,
    SIGN_IN_FAILURE: `${STATE_REDUCER_KEY}/SIGN_IN_FAILURE`,

    SIGN_UP: `${STATE_REDUCER_KEY}/SIGN_UP`,
    SIGN_UP_REQUEST: `${STATE_REDUCER_KEY}/SIGN_UP_REQUEST`,
    SIGN_UP_SUCCESS: `${STATE_REDUCER_KEY}/SIGN_UP_SUCCESS`,
    SIGN_UP_FAILURE: `${STATE_REDUCER_KEY}/SIGN_UP_FAILURE`,

    FETCH_ORG_ADMINS: `${STATE_REDUCER_KEY}/FETCH_ORG_ADMINS`,
    FETCH_ORG_ADMINS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_ORG_ADMINS_REQUEST`,
    FETCH_ORG_ADMINS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_ORG_ADMINS_SUCCESS`,
    FETCH_ORG_ADMINS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_ORG_ADMINS_FAILURE`,

    USER_PROFILE: `${STATE_REDUCER_KEY}/USER_PROFILE`,
    USER_PROFILE_REQUEST: `${STATE_REDUCER_KEY}/USER_PROFILE_REQUEST`,
    USER_PROFILE_SUCCESS: `${STATE_REDUCER_KEY}/USER_PROFILE_SUCCESS`,
    USER_PROFILE_FAILURE: `${STATE_REDUCER_KEY}/USER_PROFILE_FAILURE`

};

export const signUp = createAction(ACTION_TYPES.SIGN_UP);
export const signIn = createAction(ACTION_TYPES.SIGN_IN);
export const fetchOrgAdmins = createAction(ACTION_TYPES.FETCH_ORG_ADMINS);
