import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {

    FILTER_VESSEL: `${STATE_REDUCER_KEY}/FILTER_VESSEL`,

    FETCH_VESSEL_LIST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST`,
    FETCH_VESSEL_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_REQUEST`,
    FETCH_VESSEL_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_SUCCESS`,
    FETCH_VESSEL_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_LIST_FAILURE`,

    VESSEL_REQUEST_LIST: `${STATE_REDUCER_KEY}/VESSEL_REQUEST_LIST`,
    VESSEL_REQUEST_LIST_REQUEST: `${STATE_REDUCER_KEY}/VESSEL_REQUEST_LIST_REQUEST`,
    VESSEL_REQUEST_LIST_SUCCESS: `${STATE_REDUCER_KEY}/VESSEL_REQUEST_LIST_SUCCESS`,
    VESSEL_REQUEST_LIST_FAILURE: `${STATE_REDUCER_KEY}/VESSEL_REQUEST_LIST_FAILURE`,

    APPROVE_VESSEL: `${STATE_REDUCER_KEY}/APPROVE_VESSEL`,
    APPROVE_VESSEL_REQUEST: `${STATE_REDUCER_KEY}/APPROVE_VESSEL_REQUEST`,
    APPROVE_VESSEL_SUCCESS: `${STATE_REDUCER_KEY}/APPROVE_VESSEL_SUCCESS`,
    APPROVE_VESSEL_FAILURE: `${STATE_REDUCER_KEY}/APPROVE_VESSEL_FAILURE`,

    CREATE_VESSEL: `${STATE_REDUCER_KEY}/CREATE_VESSEL`,
    CREATE_VESSEL_REQUEST: `${STATE_REDUCER_KEY}/CREATE_VESSEL_REQUEST`,
    CREATE_VESSEL_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_VESSEL_SUCCESS`,
    CREATE_VESSEL_FAILURE: `${STATE_REDUCER_KEY}/CREATE_VESSEL_FAILURE`,

    FETCH_VESSEL_DETAILS_LIST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_LIST`,
    FETCH_VESSEL_DETAILS_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_LIST_REQUEST`,
    FETCH_VESSEL_DETAILS_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_LIST_SUCCESS`,
    FETCH_VESSEL_DETAILS_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_LIST_FAILURE`,

    FETCH_VESSEL_DETAILS_BY_ID: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_BY_ID`,
    FETCH_VESSEL_DETAILS_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_BY_ID_REQUEST`,
    FETCH_VESSEL_DETAILS_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_BY_ID_SUCCESS`,
    FETCH_VESSEL_DETAILS_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_BY_ID_FAILURE`,

    FETCH_MANAGER_PROFILE: `${STATE_REDUCER_KEY}/FETCH_MANAGER_PROFILE`,
    FETCH_MANAGER_PROFILE_REQUEST: `${STATE_REDUCER_KEY}/FETCH_MANAGER_PROFILE_REQUEST`,
    FETCH_MANAGER_PROFILE_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_MANAGER_PROFILE_SUCCESS`,
    FETCH_MANAGER_PROFILE_FAILURE: `${STATE_REDUCER_KEY}/FETCH_MANAGER_PROFILE_FAILURE`


};

export const fetchVesselList = createAction(ACTION_TYPES.FETCH_VESSEL_LIST);
export const fetchVesselRequestList = createAction(ACTION_TYPES.VESSEL_REQUEST_LIST);
export const approveVessel = createAction(ACTION_TYPES.APPROVE_VESSEL);
export const createVesselAsync = createAction(ACTION_TYPES.CREATE_VESSEL);
export const fetchVesselDetailsList = createAction(ACTION_TYPES.FETCH_VESSEL_DETAILS_LIST);
export const filterVessel = createAction(ACTION_TYPES.FILTER_VESSEL);
export const fetchVesselById = createAction(ACTION_TYPES.FETCH_VESSEL_DETAILS_BY_ID);
export const fetchManagerProfile = createAction(ACTION_TYPES.FETCH_MANAGER_PROFILE);
