import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_VESSEL_DETAILS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS`,
    FETCH_VESSEL_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_REQUEST`,
    FETCH_VESSEL_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_SUCCESS`,
    FETCH_VESSEL_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_VESSEL_DETAILS_FAILURE`,

    UPDATE_VESSEL_INSPECTION: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION`,
    UPDATE_VESSEL_INSPECTION_REQUEST: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_REQUEST`,
    UPDATE_VESSEL_INSPECTION_SUCCESS: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_SUCCESS`,
    UPDATE_VESSEL_INSPECTION_FAILURE: `${STATE_REDUCER_KEY}/UPDATE_VESSEL_INSPECTION_FAILURE`,


    SHOW_PREDICTIONS: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS`,
    SHOW_PREDICTIONS_REQUEST: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_REQUEST`,
    SHOW_PREDICTIONS_SUCCESS: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_SUCCESS`,
    SHOW_PREDICTIONS_FAILURE: `${STATE_REDUCER_KEY}/SHOW_PREDICTIONS_FAILURE`,


    FETCH_INSPECTION_DETAILS: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS`,
    FETCH_INSPECTION_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_REQUEST`,
    FETCH_INSPECTION_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_SUCCESS`,
    FETCH_INSPECTION_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_INSPECTION_DETAILS_FAILURE`,

    GET_VESSEL_INSPECTION: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION`,
    GET_VESSEL_INSPECTION_REQUEST: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_REQUEST`,
    GET_VESSEL_INSPECTION_SUCCESS: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_SUCCESS`,
    GET_VESSEL_INSPECTION_FAILURE: `${STATE_REDUCER_KEY}/GET_VESSEL_INSPECTION_FAILURE`

};

export const updateVessel = createAction(ACTION_TYPES.UPDATE_VESSEL_INSPECTION);
export const getVesselDetails = createAction(ACTION_TYPES.FETCH_VESSEL_DETAILS);
export const showPredictions = createAction(ACTION_TYPES.SHOW_PREDICTIONS);
export const getInspectionDetails = createAction(ACTION_TYPES.GET_VESSEL_INSPECTION);
